### ISSUE TITLE
转pdf时，遇到转出的pdf尺寸偏小问题

### ISSUE THREAD

**Issue by NameLi** [lampnick/doctron#10]
`html` 转 `pdf` 时，`A4` 纸大小（210mm×297mm）的 `html` 内容，转出后 `pdf`与 `image` 尺寸偏小（已设置 `DefaultMargin` 为 `0`，`DefaultPaperWidth` 换算为英寸值 `11.69291339`，高度 `paperHeight=8.2677` 英寸）
示例：
- 转 pdf 地址：<http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677>
- 正常 pdf 预览地址：<https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.pdf>
---
- 转 image 地址： <http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677>
- 正常 image 预览地址（这个有差异，是项目需求为一行，仅供参考）：<https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.png>

**Comment by lampnick** [comment]
> `html` 转 `pdf` 时，`A4` 纸大小（210mm×297mm）的 `html` 内容，转出后 `pdf`与 `image` 尺寸偏小（已设置 `DefaultMargin` 为 `0`，`DefaultPaperWidth` 换算为英寸值 `11.69291339`，高度 `paperHeight=8.2677` 英寸）
> 示例：
> 
> * 转 pdf 地址：http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677
> * 正常 pdf 预览地址：https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.pdf
> 
> * 转 image 地址： http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677
> * 正常 image 预览地址（这个有差异，是项目需求为一行，仅供参考）：https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.png

你可能需要对转换参数进行一下微调，页面大小及margin值，转换存在一定的误差。

**Comment by NameLi** [comment]
> > `html`转`pdf`时，`A4`纸大小（210mm×297mm）的`html`内容，转出后`pdf`与`image`尺寸偏小（已设置`DefaultMargin`为`0`，`DefaultPaperWidth`换算为英寸值`11.69291339`，高度`paperHeight=8.2677`英寸）
> > 示例：
> > 
> > * 转pdf地址：http: [//39.103.166.150](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) : [8080](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) /convert/ [html2pdf?u=](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) doctron&p= [lampnick&](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) url=https: [//paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677)
> > * 正常pdf预览地址：[https](https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.pdf) : [//bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.pdf](https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.pdf)
> > * 转影像地址：http: [//39.103.166.150](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) : [8080](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) /convert/ [html2image?u=](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) doctron&p= [lampnick&](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) url=https: [//paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677)
> > * 正常图片预览地址（这个有差异，是项目需求为一行，适合参考）：[https](https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.png) ://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.png[](https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.png)
> 
> 您可能需要对转换参数进行一下微调，页面大小及margin值，转换存在一定的误差。

那我目前只能通过按缩小比例换算校正尺寸了，谢谢了

**Comment by lampnick** [comment]
> > > `html`转`pdf`时，`A4`纸大小（210mm×297mm）的`html`内容，转出后`pdf`与`image`尺寸偏小（已设置`DefaultMargin`为`0`，`DefaultPaperWidth`换算为英寸值`11.69291339`，高度`paperHeight=8.2677`英寸）
> > > 示例：
> > > 
> > > * 转pdf地址：http: [//39.103.166.150](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) : [8080](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) /convert/ [html2pdf?u=](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) doctron&p= [lampnick&](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) url=https: [//paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677](http://39.103.166.150:8080/convert/html2pdf?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677)
> > > * 正常pdf预览地址：[https](https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.pdf) : [//bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.pdf](https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.pdf)
> > > * 转影像地址：http: [//39.103.166.150](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) : [8080](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) /convert/ [html2image?u=](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) doctron&p= [lampnick&](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677) url=https: [//paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677](http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https://paper.ixook.com/home.html&&marginTop=0&marginLeft=0&marginRight=0&marginbottom=0&paperwidth=11.69291339&paperHeight=8.2677)
> > > * 正常图片预览地址（这个有差异，是项目需求为一行，适合参考）：[https](https://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.png) ://bucket1-1301272873.cos.ap-shanghai.myqcloud.com/examSheet/1291560587918315520.png
> > 
> > 
> > 您可能需要对转换参数进行一下微调，页面大小及margin值，转换存在一定的误差。
> 
> 那我目前只能通过按缩小比例换算校正尺寸了，谢谢了

是的，不客气
