### ISSUE TITLE
Direct html conversion

### ISSUE THREAD

**Issue by MikeVlad6** [lampnick/doctron#13]
Hi, is there any way to pass directly the HTML code and not an URL?

Thanks!

**Comment by lampnick** [comment]
> Hi, is there any way to pass directly the HTML code and not an URL?
> 
> Thanks!

Sorry, It's not supported currently. If necessary, Maybe build a dynamic server or save as a file in doctron to support it.

**Comment by MikeVlad6** [comment]
Thanks for the reply and great work! The docker works perfect.
