### ISSUE TITLE
带参数的url没办法转换成功

### ISSUE THREAD

**Issue by chulinx** [lampnick/doctron#18]
例如grafana的这样页面http://10.206.230.7:30001/d/G9Q1Ncdnk/zhu-ji-jin-cheng-zi-yuan-jian-kong?orgId=1&refresh=10s&kiosk=tv 转换的时候日志会报如下错误
INFO] 2021/11/25 09:55 [/convert/html2pdf?u=doctron&p=lampnick&url=http://10.206.230.7:30001/d/G9Q1Ncdnk/zhu-ji-jin-cheng-zi-yuan-jian-kong?orgId=1&refresh=10s&kiosk=tv][schema: invalid path "refresh" (and 1 other error)]
[INFO] 2021/11/25 09:55 uuid:[02864717-7b67-4814-ada3-f7cb245538b8],doctron.Convert Elapsed [2.678866504s],url:[/convert/html2pdf?u=doctron&p=lampnick&url=http://10.206.230.7:30001/d/G9Q1Ncdnk/zhu-ji-jin-cheng-zi-yuan-jian-kong?orgId=1&refresh=10s&kiosk=tv]
[INFO] 2021/11/25 09:55 200 2.681220589s 10.254.207.38 GET /convert/html2pdf
[INFO] 2021/11/25 09:55 [/convert/html2pdf?u=doctron&p=lampnick&url=http://10.206.230.7:30001/d/G9Q1Ncdnk/zhu-ji-jin-cheng-zi-yuan-jian-kong?orgId=1&refresh=10s&kiosk=tv][schema: invalid path "kiosk" (and 1 other error)]
[INFO] 2021/11/25 09:55 uuid:[acbdb29a-ac2c-4135-be97-a31d07a3c74f],doctron.Convert Elapsed [2.374941014s],url:[/convert/html2pdf?u=doctron&p=lampnick&url=http://10.206.230.7:30001/d/G9Q1Ncdnk/zhu-ji-jin-cheng-zi-yuan-jian-kong?orgId=1&refresh=10s&kiosk=tv]

**Comment by lampnick** [comment]
> 

地址 urlencode 试下没有？
