### ISSUE TITLE
docker容器启动后，报错3000000

### ISSUE THREAD

**Issue by kangzhixing** [lampnick/doctron#19]
docker容器启动后，访问`http://localhost:8080/convert/html2image?u=doctron&p=lampnick&url=......`报错如下：
`{"code":30000000,"message":"context canceled","data":null}`
请问是什么原因造成的

本地通过go run启动，需要找到.doctron配置文件，这个文件默认内容是？

**Comment by lampnick** [comment]
> 

你那个 localhost在容易里面访问不了，你用能访问的 IP 试试

**Comment by nguyenphuocnhatthanh** [comment]
@lampnick I got the same issue.
How to resolve ?

**Comment by soryetong** [comment]
> docker容器启动后，访问`http://localhost:8080/convert/html2image?u=doctron&p=lampnick&url=......`报错如下： `{"code":30000000,"message":"context canceled","data":null}` 请问是什么原因造成的
> 
> 本地通过go run启动，需要找到.doctron配置文件，这个文件默认内容是？

请问解决了嘛
