### ISSUE TITLE
Tag 0.3.1

### ISSUE THREAD

**Issue by testlorenzospa** [lampnick/doctron#20]
Hello.

Can I use the latest release 0.3.1?
In this [page](https://github.com/lampnick/doctron/tags) the label "Verified" isn't present on the relative tag.
Let me know.

Many thanks.

**Comment by lampnick** [comment]
> Hello.
> 
> Can I use the latest release 0.3.1? In this [page](https://github.com/lampnick/doctron/tags) the label "Verified" isn't present on the relative tag. Let me know.
> 
> Many thanks.

Yes, You can use v0.3.1

**Comment by testlorenzospa** [comment]
Hello @lampnick.

Thanks for this confirm.
