### ISSUE TITLE
你好请问这个docker启动后访问对应的转换请求日志记录在哪里能看到

### ISSUE THREAD

**Issue by intern** [lampnick/doctron#21]
你好请问这个docker启动后访问对应的转换请求日志(比如类似nginx日志)记录在哪里能看到, 我现在是在docker 启动日志里面有, 但是在容器内部没有看到日志. 请问哪里可以配置或者那个容器内部 地址可以看到呢?

**Comment by lampnick** [comment]
> 

暂时还没支持可配置的，都是 console 输出。后续空了可以开放出来
