### ISSUE TITLE
 Config File ".doctron" Not Found in "[C:\\Users\\Administrator]"

### ISSUE THREAD

**Issue by Mrhwj** [lampnick/doctron#25]
Config File ".doctron" Not Found in "[C:\\Users\\Administrator]"

**Comment by lampnick** [comment]
> Config File ".doctron" Not Found in "[C:\Users\Administrator]"

You can give the  --config param or copy https://github.com/lampnick/doctron/blob/master/conf/default.yaml to C:\Users\Administrator folder.
