### ISSUE TITLE
go运行报错

### ISSUE THREAD

**Issue by kp16347** [lampnick/doctron#26]
go运行包下面的错误
[read config ReadInConfig] err: Config File ".doctron" Not Found in "[C:\\Users\\iso]"
如何解？

**Comment by lampnick** [comment]
> go运行包下面的错误 [read config ReadInConfig] err: Config File ".doctron" Not Found in "[C:\Users\iso]" 如何解？

将 conf 下面的 default.yaml 复制到C:\Users\iso这个目录下，命名为".doctron.yaml"

**Comment by lampnick** [comment]
> > go运行包下面的错误 [read config ReadInConfig] err: Config File ".doctron" Not Found in "[C:\Users\iso]" 如何解？
> 
> 将 conf 下面的 default.yaml 复制到C:\Users\iso这个目录下，命名为".doctron.yaml"



> > go运行包下面的错误 [read config ReadInConfig] err: Config File ".doctron" Not Found in "[C:\Users\iso]" 如何解？
> 
> 将 conf 下面的 default.yaml 复制到C:\Users\iso这个目录下，命名为".doctron.yaml"

或者启动时指定配置文件--config
