### ISSUE TITLE
启动后报错

### ISSUE THREAD

**Issue by fengweng** [lampnick/doctron#27]
使用go get 部署，成功启动后，执行转换时候报错
{"code":30000000,"message":"exec: \"google-chrome\": executable file not found in $PATH","data":null}

**Comment by lampnick** [comment]
> 使用go get 部署，成功启动后，执行转换时候报错 {"code":30000000,"message":"exec: "google-chrome": executable file not found in $PATH","data":null}

你本地的话需要安装chromium

**Comment by lampnick** [comment]
> 使用go get 部署，成功启动后，执行转换时候报错 {"code":30000000,"message":"exec: "google-chrome": executable file not found in $PATH","data":null}

centos : yum -y install chromium
