### ISSUE TITLE
不用docker我应该怎么部署到centos系统上呢？

### ISSUE THREAD

**Issue by shuiche-it** [lampnick/doctron#29]
我打包后启动程序没有报错，调用接口时提示：
<img width="646" alt="image" src="https://user-images.githubusercontent.com/10776422/172549679-276f6e66-cf76-4a6e-b05d-c8eb3d33bae9.png">
我应该下载什么程序来保证正常运行呢？

**Comment by lampnick** [comment]
> 

你需要下载一下chromium,添加到$PATH 下
