### ISSUE TITLE
go run main.go启动报错了

### ISSUE THREAD

**Issue by clickandthink** [lampnick/doctron#30]
[read config ReadInConfig] err: Config File ".doctron" Not Found in "[/root]"
exit status 1
go version go1.18.3 linux/amd64
centos

**Comment by lampnick** [comment]
> [read config ReadInConfig] err: Config File ".doctron" Not Found in "[/root]" exit status 1 go version go1.18.3 linux/amd64 centos

看下这个 issue https://github.com/lampnick/doctron/issues/26
