### ISSUE TITLE
微信图片懒加载无法截图

### ISSUE THREAD

**Issue by tomorrowbaby** [lampnick/doctron#33]
如下连接
https://mp.weixin.qq.com/s?__biz=MzU3MjQ3NjkwOQ==&mid=2247588095&idx=1&sn=124c9d05b0de163fbb6f3949c1e0d155&chksm=fcd3847dcba40d6b8a3701dc6354b4cf543735ca6bd4e18fd7b51c614c1781412cf85976d778#rd

在进入页面下方的图片截图时并未加载

**Comment by lampnick** [comment]
> 没找到解决方法

**Comment by lampnick** [comment]
thanks for your pr.
