### ISSUE TITLE
[read config ReadInConfig] err: Config File ".doctron"

### ISSUE THREAD

**Issue by hcr707305003** [lampnick/doctron#34]
![O~@3GUJQKGQJM`@ RI7_QRT](https://user-images.githubusercontent.com/22547038/180899629-eefe4ed9-784b-40ea-8d57-516a7114d4cf.png)

**Comment by lampnick** [comment]
> ![O~@3GUJQKGQJM`@ RI7_QRT](https://user-images.githubusercontent.com/22547038/180899629-eefe4ed9-784b-40ea-8d57-516a7114d4cf.png)

like this issue,https://github.com/lampnick/doctron/issues/25
