### ISSUE TITLE
接口可以传递HTML文本内容不

### ISSUE THREAD

**Issue by boskt** [lampnick/doctron#35]
目前只看到接口可以传递URL地址，不知道是否可以传递HTML文本内容转换成PDF

**Comment by lampnick** [comment]
not support.

**Comment by boskt** [comment]
能否支持添加接口参数增加一个数组字段用于接收一组HTML内容，在后端将HTML保存为一组临时的文件，再循环用chromedp.Navigate("/home/admin/index.html"),读取该文件，转换完成后删除临时文件夹，以此来支持上述功能？

**Comment by Zzaniu** [comment]
是否可以添加一个[]byte的参数, 使支持上传本地的html文件

**Comment by lampnick** [comment]
html 内容的话，如果里面有链接也是需要请求处理的。
