### ISSUE TITLE
Render Icon

### ISSUE THREAD

**Issue by phikhanhcr** [lampnick/doctron#36]
I have an issue with doctron, Doctron can't render emoji 
Somebody can help me to fix it? 
Thanks
example: 🛍 🛍🛍

**Comment by lampnick** [comment]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/15793076/186414700-3cfcf24a-e348-4a40-8c16-d259d3b46b7f.png">
hava a try ,using this issue url to generate.( http://doctron.lampnick.com/  )
