### ISSUE TITLE
Error after generation

### ISSUE THREAD

**Issue by testlorenzospa** [lampnick/doctron#39]
Hello.

I have this issue.
When I try to generate an image or a pdf, in the output of the generated file I can read this string

{"code":30000000,"message":"worker run process failed.job request timed out","data":null}

What type of error is this? What can I do to solve it?

Thanks.

**Comment by lampnick** [comment]
> Hello.
> 
> I have this issue. When I try to generate an image or a pdf, in the output of the generated file I can read this string
> 
> {"code":30000000,"message":"worker run process failed.job request timed out","data":null}
> 
> What type of error is this? What can I do to solve it?
> 
> Thanks.

Maybe worker poll full.
