### ISSUE TITLE
the master branch  is not work

### ISSUE THREAD

**Issue by chengyizhoucode** [lampnick/doctron#42]
just fllow you example  but it dosen't work

<img width="750" alt="image" src="https://user-images.githubusercontent.com/54266096/208586868-5f477edc-da1a-4d99-b164-382a0480434e.png">

**Comment by lampnick** [comment]
How did you deployed it?

**Comment by LL-lanbusite** [comment]
{"code":20000000,"message":"no need to upload","data":null} 这是怎么回事

**Comment by lampnick** [comment]
> no need to upload

没有配置阿里云 oss key
