### ISSUE TITLE
自定义页眉页脚

### ISSUE THREAD

**Issue by shuiche-it** [lampnick/doctron#45]
我看代码中有HeaderTemplate和FooterTemplate两个参数，但是说明文档中没有放出来这两个参数，是什么原因呢？

**Comment by shuiche-it** [comment]
我查询了源代码，发现HeaderTemplate和FooterTemplate只是被定义了，没有在任何地方被使用。是这样的吗？

**Comment by lampnick** [comment]
暂时没有开放出来
