### ISSUE TITLE
[bug] html2image for long page fail

### ISSUE THREAD

**Issue by TailendWong** [lampnick/doctron#48]
It's not work(timeout) when the web page is a bit long. 
But it is not really timeout, page is not very long, however, I run the project in GoLand with the same web page, it convert image successfull .

url: http://39.103.166.150:8080/convert/html2image?u=doctron&p=lampnick&url=https%3A%2F%2Fwww.cnblogs.com%2Fgrkin%2Farchive%2F2013%2F03%2F17%2F2964964.html

_Originally posted by @TailendWong in https://github.com/lampnick/doctron/issues/37#issuecomment-1560375350_

**Comment by lampnick** [comment]
Can you try on your own linux server?

**Comment by TailendWong** [comment]
I meet the same issue, i build a docker image from Dockerfile that is in the project, then i run it on my own linux server. 

I got response like this: 
`{"code":30000000,"message":"worker run process failed.job request timed out","data":null}`

Actually, i try change config `convertTimeout: 600`, it is also return 30000000 like above. So, i think it may not be timeout.

**Comment by lampnick** [comment]
You can increase the timeout time in the configuration file. convertTimeout: 20

**Comment by TailendWong** [comment]
> You can increase the timeout time in the configuration file. convertTimeout: 20

Thanks for your reply
