### ISSUE TITLE
可以配置页面加载完以后等待指定时间后再生成图片吗

### ISSUE THREAD

**Issue by 287400117** [lampnick/doctron#6]
我用 vue，每次生成的图片只是基础页面，数据都还没加载出来，可以配置页面加载完以后等待指定时间后再生成图片吗

**Comment by lampnick** [comment]
目前还不支持，后续会增加通过判断页面指定元素是否加载完成或者通过js判断ajax是否加载完成再去生成pdf或者图片。

**Comment by lampnick** [comment]
> 我用 vue，每次生成的图片只是基础页面，数据都还没加载出来，可以配置页面加载完以后等待指定时间后再生成图片吗

目前还不支持，后续会增加通过判断页面指定元素是否加载完成或者通过js判断ajax是否加载完成再去生成pdf或者图片。

**Comment by 287400117** [comment]
预计什么时候会支持呢

**Comment by lampnick** [comment]
> 预计什么时候会支持呢

这段时间空了看一下

**Comment by wangcheng0509** [comment]
我也遇到了同样的问题，看了一下底层源码，是一系列任务连续在chrome里执行的，我自己改动的话要改的地方好像很多

**Comment by lampnick** [comment]
> 我也遇到了同样的问题，看了一下底层源码，是一系列任务连续在chrome里执行的，我自己改动的话要改的地方好像很多

是的，目前调试发现设置等待时长有点问题，还在找解决方案。

**Comment by xenon007** [comment]
Hello!
I also encountered the same problem. Waiting enhancement of timeout.

Big thanks

**Comment by lampnick** [comment]
> Hello!
> I also encountered the same problem. Waiting enhancement of timeout.
> 
> Big thanks

Okay.

**Comment by lampnick** [comment]
@xenon007 @287400117 @wangcheng0509 Do you expect to wait for a period of time to convert  or wait for the specified element in the page to load successfully?

**Comment by xenon007** [comment]
> @xenon007 @287400117 @wangcheng0509 Do you expect to wait for a period of time to convert or wait for the specified element in the page to load successfully?

I'm expect possible setting of timeout for page loading. Some pages rendered with half of design stuff or without loaded data from api

Render mechanism works awesome =)

PS
I'm using docker container with compose

**Comment by lampnick** [comment]
> > @xenon007 @287400117 @wangcheng0509 Do you expect to wait for a period of time to convert or wait for the specified element in the page to load successfully?
> 
> I'm expect possible setting of timeout for page loading. Some pages rendered with half of design stuff or without loaded data from api
> 
> Render mechanism works awesome =)
> 
> PS
> I'm using docker container with compose

Got it.

**Comment by lampnick** [comment]
@xenon007 @287400117 @wangcheng0509  Hi,guys, Please pull the latest image(lampnick/doctron:v0.3.0-alpine or lampnick/doctron:latest) and try again.I'll close the issue. If you have any problems please open an new issue. Thank you!
