### ISSUE TITLE
Timeout of loading page or something else

### ISSUE THREAD

**Issue by xenon007** [lampnick/doctron#8]
Hello again!
After update to v0.3.0-alpine i try to render hard page with many data loading per AJAX

After that i have a 2 issue
1) on first start `http://development-docker-monitoring:10000/convert/html2image?u=ddd&p=ddd&url=http://dev-monitoring-axibase:8080/pub/db/widgets_BIGBOARD?do-not-track=true&theme=black` i have a result page
```{"code":30000000,"message":"worker run process failed.job request timed out","data":null}``` and logs of compose:
```
ddd-render | Now listening on: http://0.0.0.0:10000
ddd-render | Application started. Press CTRL+C to shut down.
ddd-render | [INFO] 2021/02/04 14:33 [/convert/html2image?u=ddd&p=ddd&url=http://dev-monitoring-axibase:8080/pub/db/widgets_BIGBOARD?do-not-track=true&theme=black][schema: invalid path "theme"]
ddd-render | [INFO] 2021/02/04 14:33 200 10.000796493s 172.16.0.2 GET /convert/html2image 
```

2) after URL ENCODE an URL i have a issue on top and https://prnt.sc/ya5ker after refresh with logs:
```ddd-render | [INFO] 2021/02/04 14:33 uuid:[785bf403-db54-4271-b68e-ca12d9cd4ecb],doctron.Convert Elapsed [10.025282547s],url:[/convert/html2image?u=ddd&p=ddd&url=http://dev-monitoring-axibase:8080/pub/db/widgets_BIGBOARD?do-not-track=true&theme=black]
ddd-render | [INFO] 2021/02/04 14:35 200 10.001182781s 172.16.0.2 GET /convert/html2image
ddd-render | [INFO] 2021/02/04 14:35 uuid:[c0207652-5f7f-4065-9f9b-874eaa92e83a],doctron.Convert Elapsed [10.019974817s],url:[/convert/html2image?u=ddd&p=ddd&url=http%3A%2F%2Fdev-monitoring-axibase%3A8080%2Fpub%2Fdb%2Fwidgets_BIGBOARD%3Fdo-not-track%3Dtrue%26theme%3Dblack]
ddd-render | [INFO] 2021/02/04 14:39 uuid:[3a2bf1ab-8a60-4b4e-937a-a796311723ed],doctron.Convert Elapsed [3.361823045s],url:[/convert/html2image?u=ddd&p=ddd&url=http%3A%2F%2Fdev-monitoring-axibase%3A8080%2Fpub%2Fdb%2Fwidgets_BIGBOARD%3Fdo-not-track%3Dtrue%26theme%3Dblack]
ddd-render | [INFO] 2021/02/04 14:39 200 3.366392817s 172.16.0.2 GET /convert/html2image
```

Timeout update to v0.3.0-alpine don't help correctly

**Comment by lampnick** [comment]
> Hello again!
> After update to v0.3.0-alpine i try to render hard page with many data loading per AJAX
> 
> After that i have a 2 issue
> 
> 1. on first start `http://development-docker-monitoring:10000/convert/html2image?u=ddd&p=ddd&url=http://dev-monitoring-axibase:8080/pub/db/widgets_BIGBOARD?do-not-track=true&theme=black` i have a result page
>    `{"code":30000000,"message":"worker run process failed.job request timed out","data":null}` and logs of compose:
> 
> ```
> ddd-render | Now listening on: http://0.0.0.0:10000
> ddd-render | Application started. Press CTRL+C to shut down.
> ddd-render | [INFO] 2021/02/04 14:33 [/convert/html2image?u=ddd&p=ddd&url=http://dev-monitoring-axibase:8080/pub/db/widgets_BIGBOARD?do-not-track=true&theme=black][schema: invalid path "theme"]
> ddd-render | [INFO] 2021/02/04 14:33 200 10.000796493s 172.16.0.2 GET /convert/html2image 
> ```
> 
> 1. after URL ENCODE an URL i have a issue on top and https://prnt.sc/ya5ker after refresh with logs:
> 
> ```
> ddd-render | [INFO] 2021/02/04 14:35 200 10.001182781s 172.16.0.2 GET /convert/html2image
> ddd-render | [INFO] 2021/02/04 14:35 uuid:[c0207652-5f7f-4065-9f9b-874eaa92e83a],doctron.Convert Elapsed [10.019974817s],url:[/convert/html2image?u=ddd&p=ddd&url=http%3A%2F%2Fdev-monitoring-axibase%3A8080%2Fpub%2Fdb%2Fwidgets_BIGBOARD%3Fdo-not-track%3Dtrue%26theme%3Dblack]
> ddd-render | [INFO] 2021/02/04 14:39 uuid:[3a2bf1ab-8a60-4b4e-937a-a796311723ed],doctron.Convert Elapsed [3.361823045s],url:[/convert/html2image?u=ddd&p=ddd&url=http%3A%2F%2Fdev-monitoring-axibase%3A8080%2Fpub%2Fdb%2Fwidgets_BIGBOARD%3Fdo-not-track%3Dtrue%26theme%3Dblack]
> ddd-render | [INFO] 2021/02/04 14:39 200 3.366392817s 172.16.0.2 GET /convert/html2image
> ```
> 
> Timeout update to v0.3.0-alpine don't help correctly

First of all, your website looks like slowly,and your doctron.yaml config's timeout maybe 10 seconds.You could open the fllowing url `http://dev-monitoring-axibase:8080/pub/db/widgets_BIGBOARD?do-not-track=true&theme=black`  in your browser to compute time elapsed.
Secondly, if you want to wait a minute after page loaded, you must pass the param `waitingTime=?` in v0.3.0. The convert url like this `http://domain/convert/html2image?u=doctron&p=lampnick&url=http%3A%2F%2Fdoctron.lampnick.com%2Fdoctron.html&waitingTime=1000`.
Have a try, if you still have problem, give me a message.

**Comment by lampnick** [comment]
@xenon007 Has the problem been solved？
