### ISSUE TITLE
LocalPath in URL

### ISSUE THREAD

**Issue by shwetahealthians** [lampnick/doctron#9]
can i give my local file path in URL for generating PDF:
i am using : http://0.0.0.0:8080/convert/html2pdf?u=doctron&p=lampnick&url=file%3A%2F%2F%2Fhome%2Fshweta%2FDownloads%2Fvital_5fb7c71130463_20112020070929.htmll

But it gives m blank PDF instead of my html page.

**Comment by lampnick** [comment]
> can i give my local file path in URL for generating PDF:
> i am using : http://0.0.0.0:8080/convert/html2pdf?u=doctron&p=lampnick&url=file%3A%2F%2F%2Fhome%2Fshweta%2FDownloads%2Fvital_5fb7c71130463_20112020070929.htmll
> 
> But it gives m blank PDF instead of my html page.

Unfortunately! Doctron can't reach the file in the local mechine because it's deployed in the container.
